### ISSUE TITLE
Never-ending Exporting Bug

### ISSUE THREAD

**Issue by RayAleciana** [IngoHHacks/IGCCMod#1]
**_Once you create a card, You are stuck permanently on the Exporting screen, I'm using the Thunderstore mod manager, This happens most of the time. In the Bepinex console, It ends with this message as the game supposedly breaks there:_**

[Error  : Unity Log] MissingMethodException: void APIPlugin.NewCard.Add(string,System.Collections.Generic.List`1<DiskCardGame.CardMetaCategory>,DiskCardGame.CardComplexity,CardTemple,string,int,int,string,bool,int,int,int,System.Collections.Generic.List`1<DiskCardGame.GemType>,DiskCardGame.SpecialStatIcon,System.Collections.Generic.List`1<DiskCardGame.Tribe>,System.Collections.Generic.List`1<DiskCardGame.Trait>,System.Collections.Generic.List`1<DiskCardGame.SpecialTriggeredAbility>,System.Collections.Generic.List`1<DiskCardGame.Ability>,System.Collections.Generic.List`1<APIPlugin.AbilityIdentifier>,DiskCardGame.EvolveParams,string,DiskCardGame.TailParams,DiskCardGame.IceCubeParams,bool,bool,System.Collections.Generic.List`1<DiskCardGame.CardAppearanceBehaviour/Appearance>,UnityEngine.Texture2D,UnityEngine.Texture2D,UnityEngine.Texture,UnityEngine.Texture2D,UnityEngine.GameObject,System.Collections.Generic.List`1<UnityEngine.Texture>,APIPlugin.EvolveIdentifier,APIPlugin.IceCubeIdentifier,APIPlugin.TailIdentifier)
Stack trace:
IGCCMod.Plugin+PostDeathCardPatch+<FinalizeCard>d__3.MoveNext () (at <2963b467f3ed499da7afc61004bb2e70>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by IngoHHacks** [comment]
IGCC and JSONLoader are not yet updated to work with API version 1.12.
Resolution for now is to use API version 1.11.
