### ISSUE TITLE
View zooms out bug

### ISSUE THREAD

**Issue by JBB0** [IngoHHacks/IGCCMod#2]
### When creating a card, every time you select an option the view zooms out ->
(eventually making the screen go black and the game unplayable), the view also moves up which prevents you from selecting a sigil.
![Untitled](https://user-images.githubusercontent.com/49321818/145319871-05c19186-aa8a-47dc-bc57-ef5cebd57caa.png)

**List of installed mods:**

- BepInExPack_Inscryption
- API
- Visually_Stackable_Sigils
- Dialog_Remover
- Skip_Start_Screen
- JSONCardLoader
- Animal_Expansion
- Unlock_All
- Upgradeable_Starter_Decks
- Mythology_Card_Pack
- InGame_Card_Creator
- SigilADay
- Japanese_Mythology_CardPack
- ExtendedMaps

**Comment by IngoHHacks** [comment]
Caused by Dialog_Remover
