### ISSUE TITLE
Kaycee Beta Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [IngoHHacks/IGCCMod#3]
I think an easy way to allow adding cards to the game for kaycee mod would be to make a hotkey for card creation maybe home key? Also please remove all leshy noises.

**Comment by IngoHHacks** [comment]
Kaycee's Mod support is being worked on.
I will consider adding a keybind, but the current process of entering the card creator is already quite fast.
I won't be removing Leshy noises as that's not this mod's responsibility.

**Comment by IngoHHacks** [comment]
Added v1.2.0 (and exactly 1.2.0 - not newer) to support Kaycee's Mod.
Keybinds might be added in the planned 2.0 rewrite.
