### ISSUE TITLE
Stuck With Leshy Bug

### ISSUE THREAD

**Issue by breakbinary** [IngoHHacks/IGCCMod#4]
Hi! I've had a problem where I can't select anything after I enter in. Leshy says welcome to the card creator and then I'm locked, I can't do anything except exit the game. I've gotten it to kind of work one time except there were no cards to put my stats on, but that was when I first downloaded it. I've tried putting it into the games files manually and using the Thunderstore mod manager. I also checked to see if I have the required files, and I do. Thank you!

**Comment by IngoHHacks** [comment]
Please include the mod list and log/error when this issue occurs.

**Comment by Gangano** [comment]
I have the same problem. the log say this:

[Error  : Unity Log] MissingMethodException: void SaveFile.NewPart1Run()
Stack trace:
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by Gangano** [comment]
My mod are:
API_dev-API
IngoH-Badly_Translated_Inscryption
IngoH-InGame_Card_Creator
IngoH-Language_Loader
IngoH-Modded_Save_Fixer
Kopie-Smalltweak_Hammer
MADH95Mods-JSONCardLoader
SpecialAPI-BoonAPI
SpecialAPI-NodeAPI

**Comment by IngoHHacks** [comment]
> I have the same problem. the log say this:
> 
> [Error : Unity Log] MissingMethodException: void SaveFile.NewPart1Run() Stack trace: UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

That means your Inscryption is outdated. Updating to V1.08 should fix it.

**Comment by Gangano** [comment]
Ok, l update it and now work thank you.

**Comment by Chaosyr** [comment]
Close this?
