### ISSUE TITLE
stops after selecting health

### ISSUE THREAD

**Issue by scrybeofteeth** [IngoHHacks/IGCCMod#6]
[Error  : Unity Log] MissingFieldException: Field 'APIPlugin.NewAbility.abilities' not found.
Stack trace:
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

the game soft locks me with me facing the cards, but the cards for abilities never show up.

**Comment by IngoHHacks** [comment]
Caused by the Kaycee's Mod update. Will be fixed soon.
